name: Vimプラグイン読書会
markdown: rdiscount
baseurl: /reading-vimplugin

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
