name: Vimプラグイン読書会
markdown: rdiscount
base-url: /reading-vimplugin/

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
